[big]*i.     Abstract*

<abstract>

[big]*ii.    Keywords*

The following are keywords to be used by search engines and document catalogues.

ogcdoc, OGC document,  <tags separated by commas>

[big]*iii.   Preface*

The OGC Web API architecture centers around decoupled microservices that provide functionality via RESTful APIs with a JSON payload. Small engineering teams own, deploy and operate these microservices in their own platforms. Our APIs most purely express what these systems do, and are therefore highly valuable business assets.

With this in mind, we’ve adopted "API First" as one of our key engineering principles. Microservices development begins with API definition outside the code and ideally involves ample peer-review feedback to achieve high-quality APIs. API First encompasses a set of quality-related standards and fosters a peer review culture including a lightweight review procedure. We encourage our teams to follow them to ensure that our APIs:

* are easy to understand and learn
* are general and abstracted from specific implementation and use cases
* are robust and easy to use
* have a common look and feel
* follow a consistent RESTful style and syntax
* are consistent with other teams’ APIs and our global architecture

Ideally, all OGC APIs will look like the same author created them.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
====
[big]*iv.    Submitting organizations*

The following organizations submitted this Document to the Open Geospatial Consortium (OGC):

Organization name(s)

[big]*v.     Submitters*

All questions regarding this submission should be directed to the editor or the submitters:

Name  Affiliation
